import {
  DispatchQueue,
  RideNode,
  VEHICLE_BY_TYPE,
  calculateFare,
  euclideanDistance,
  loadSurge,
  type DemandLevel,
  type Driver,
  type DriverStatus,
  type Point,
  type VehicleType,
} from "./dsa";

export interface LogEntry {
  id: string;
  time: string;
  message: string;
  operation: "ENQUEUE" | "DEQUEUE" | "CANCEL" | "LOOKUP" | "PRICE" | "SYSTEM";
  complexity: string;
}

export interface Pricing {
  baseFare: number;
  ratePerUnit: number;
}

export interface Stats {
  matched: number;
  cancelled: number;
}

export interface CancelStep {
  title: string;
  detail: string;
}

export interface RiderProfile {
  name: string;
  phone: string;
  email: string;
  home: Point;
  work: Point;
  preferredVehicle: VehicleType;
}

export interface HistoryEntry {
  rideId: string;
  riderName: string;
  vehicleType: VehicleType;
  driverId: string;
  driverName: string;
  fare: number;
  distance: number;
  at: number;
  outcome: "Matched" | "Cancelled";
}

const STORAGE_KEY = "rideshare-dispatch-state-v2";

function nowTime() {
  return new Date().toLocaleTimeString("en-GB", { hour12: false });
}

let idCounter = 0;
function uid() {
  idCounter += 1;
  return `${Date.now().toString(36)}-${idCounter}`;
}

const DEFAULT_PROFILE: RiderProfile = {
  name: "Bhuvana Rani",
  phone: "+91 98765 43210",
  email: "bhuvana@campus.edu",
  home: { x: 3, y: 4 },
  work: { x: 15, y: 12 },
  preferredVehicle: "Cab Mini",
};

/** Drivers already on the road when the app first boots. */
const SEED_DRIVERS: Array<{
  name: string;
  x: number;
  y: number;
  vehicleType: VehicleType;
  vehicleNumber: string;
  rating: number;
  trips: number;
}> = [
  { name: "Ravi Kumar", x: 5, y: 8, vehicleType: "Cab Mini", vehicleNumber: "TN 09 AB 4421", rating: 4.8, trips: 1243 },
  { name: "Meena Iyer", x: 12, y: 3, vehicleType: "Bike", vehicleNumber: "TN 07 CH 8890", rating: 4.9, trips: 2104 },
  { name: "Arun Das", x: 2, y: 14, vehicleType: "Auto", vehicleNumber: "TN 01 KL 1120", rating: 4.6, trips: 870 },
  { name: "Sneha Rao", x: 18, y: 11, vehicleType: "Cab Sedan", vehicleNumber: "TN 10 SR 3345", rating: 4.7, trips: 1562 },
  { name: "Karthik S", x: 9, y: 6, vehicleType: "Cab SUV", vehicleNumber: "TN 22 XV 7781", rating: 4.5, trips: 640 },
  { name: "Farah Khan", x: 15, y: 17, vehicleType: "Premium", vehicleNumber: "TN 05 PR 0001", rating: 5.0, trips: 388 },
  { name: "Imran Ali", x: 7, y: 16, vehicleType: "Parcel", vehicleNumber: "TN 11 PD 6620", rating: 4.4, trips: 955 },
];

class SimulationStore {
  queue = new DispatchQueue();
  driverMap: Map<string, Driver> = new Map();
  logs: LogEntry[] = [];
  pricing: Pricing = { baseFare: 50, ratePerUnit: 15 };
  stats: Stats = { matched: 0, cancelled: 0 };
  rideCounter = 100;
  driverCounter = 0;
  profile: RiderProfile = { ...DEFAULT_PROFILE };
  history: HistoryEntry[] = [];
  /** last cancellation walkthrough (generated by the real algorithm) */
  lastCancelSteps: CancelStep[] = [];
  lastCancelledId: string | null = null;
  hydrated = false;

  version = 0;
  private listeners = new Set<() => void>();

  subscribe = (cb: () => void) => {
    this.listeners.add(cb);
    return () => this.listeners.delete(cb);
  };

  getVersion = () => this.version;

  private emit(persist = true) {
    this.version++;
    if (persist) this.persist();
    this.listeners.forEach((l) => l());
  }

  log(message: string, operation: LogEntry["operation"], complexity: string) {
    this.logs = [
      { id: uid(), time: nowTime(), message, operation, complexity },
      ...this.logs,
    ].slice(0, 200);
  }

  // ---------------- pricing ----------------

  /** surge = queue size ÷ available drivers (clamped) — O(1) */
  get loadSurge(): number {
    return loadSurge(this.queue.size, this.availableCount);
  }

  /**
   * System-computed demand level — derived from LIVE simulation state:
   *   pressure   = waiting rides ÷ available drivers
   *   busyRatio  = busy drivers ÷ total drivers
   * Riders never pick this manually. O(1)
   */
  get demandLevel(): DemandLevel {
    const total = this.driverMap.size;
    const available = this.availableCount;
    const busyRatio = total > 0 ? (total - available) / total : 1;
    const pressure = available > 0 ? this.queue.size / available : this.queue.size + 2;
    const score = pressure + busyRatio * 1.5;
    if (score >= 2.5) return "Very High";
    if (score >= 1.2) return "High";
    if (score >= 0.45) return "Normal";
    return "Low";
  }

  /** Human readable reason for the current demand level. */
  get demandReason(): string {
    const total = this.driverMap.size;
    const busy = total - this.availableCount;
    return `${this.queue.size} waiting · ${this.availableCount} free / ${total} drivers (${busy} busy)`;
  }

  quote(input: {
    pickup: Point;
    drop: Point;
    demandLevel: DemandLevel;
    vehicleType: VehicleType;
  }) {
    const distance = euclideanDistance(input.pickup, input.drop);
    const vehicle = VEHICLE_BY_TYPE[input.vehicleType];
    const load = this.loadSurge;
    const fare = calculateFare(
      distance,
      input.demandLevel,
      this.pricing.baseFare,
      this.pricing.ratePerUnit,
      vehicle.multiplier,
      load,
    );
    return { distance, fare, load, vehicle };
  }

  // ---------------- rides ----------------

  nextRideId(): string {
    return `RIDE-${this.rideCounter + 1}`;
  }

  addRide(input: {
    riderName: string;
    pickup: Point;
    drop: Point;
    demandLevel: DemandLevel;
    vehicleType: VehicleType;
  }): RideNode {
    const name = input.riderName.trim();
    if (!name) throw new Error("Rider name cannot be empty.");
    const coords = [input.pickup.x, input.pickup.y, input.drop.x, input.drop.y];
    if (coords.some((c) => !Number.isFinite(c))) {
      throw new Error("Coordinates must be valid numbers.");
    }
    if (!VEHICLE_BY_TYPE[input.vehicleType]) {
      throw new Error("Please choose a valid vehicle type.");
    }
    if (this.pricing.baseFare < 0 || this.pricing.ratePerUnit < 0) {
      throw new Error("Pricing values cannot be negative.");
    }
    const { distance, fare } = this.quote(input);
    this.rideCounter += 1;
    const node = new RideNode({
      rideId: `RIDE-${this.rideCounter}`,
      riderName: name,
      pickup: input.pickup,
      drop: input.drop,
      distance: Math.round(distance * 100) / 100,
      fare,
      demandLevel: input.demandLevel,
      vehicleType: input.vehicleType,
    });
    this.queue.enqueue(node);
    this.log(
      `${node.rideId} (${input.vehicleType}) added to queue (tail insert)`,
      "ENQUEUE",
      "O(1)",
    );
    this.emit();
    return node;
  }

  cancelRide(rideId: string): CancelStep[] {
    const node = this.queue.rideMap.get(rideId);
    if (!node) {
      throw new Error(`Ride "${rideId}" does not exist in the dispatch queue.`);
    }
    const prevId = node.prev?.rideId ?? "HEAD";
    const nextId = node.next?.rideId ?? "TAIL";

    const steps: CancelStep[] = [
      { title: "STEP 1 — Request", detail: `User requests cancellation of ${rideId}` },
      { title: "STEP 2 — Hash Map lookup", detail: `rideMap.get("${rideId}")  →  O(1)` },
      { title: "STEP 3 — Node found", detail: `Direct reference to node ${rideId} obtained` },
      {
        title: "STEP 4 — Read pointers",
        detail: `${rideId}.prev = ${prevId}   |   ${rideId}.next = ${nextId}`,
      },
      {
        title: "STEP 5 — Reconnect",
        detail:
          `${prevId === "HEAD" ? `head = ${nextId}` : `${prevId}.next = ${nextId}`}  |  ` +
          `${nextId === "TAIL" ? `tail = ${prevId}` : `${nextId}.prev = ${prevId}`}`,
      },
      { title: "STEP 6 — Delete entry", detail: `rideMap.delete("${rideId}")` },
    ];

    this.queue.cancel(rideId);
    this.stats.cancelled += 1;
    this.history = [
      {
        rideId: node.rideId,
        riderName: node.riderName,
        vehicleType: node.vehicleType,
        driverId: "—",
        driverName: "—",
        fare: node.fare,
        distance: node.distance,
        at: Date.now(),
        outcome: "Cancelled" as const,
      },
      ...this.history,
    ].slice(0, 100);
    this.lastCancelSteps = steps;
    this.lastCancelledId = rideId;
    this.log(`${rideId} cancelled`, "CANCEL", "O(1)");
    this.emit();
    return steps;
  }

  /**
   * Match the head of the queue with an Available driver of the requested
   * vehicle class (nearest pickup wins the tie-break).
   */
  matchNextRide(): { ride: RideNode; driver: Driver } {
    if (this.queue.isEmpty()) {
      throw new Error("No ride requests in queue.");
    }
    const head = this.queue.peek()!;
    let best: Driver | undefined;
    let bestDist = Infinity;
    for (const driver of this.driverMap.values()) {
      if (driver.status !== "Available") continue; // O(1) status lookup per driver
      if (driver.vehicleType !== head.vehicleType) continue;
      const d = euclideanDistance(
        { x: driver.locationX, y: driver.locationY },
        head.pickup,
      );
      if (d < bestDist) {
        bestDist = d;
        best = driver;
      }
    }
    if (!best) {
      throw new Error(
        `No available ${head.vehicleType} driver for ${head.rideId}. Free a driver or register one.`,
      );
    }
    const ride = this.queue.dequeue()!;
    ride.status = "Matched";
    ride.assignedDriverId = best.driverId;
    best.status = "Busy";
    best.currentRide = ride.rideId;
    best.trips += 1;
    this.driverMap.set(best.driverId, best);
    this.stats.matched += 1;
    this.history = [
      {
        rideId: ride.rideId,
        riderName: ride.riderName,
        vehicleType: ride.vehicleType,
        driverId: best.driverId,
        driverName: best.name,
        fare: ride.fare,
        distance: ride.distance,
        at: Date.now(),
        outcome: "Matched" as const,
      },
      ...this.history,
    ].slice(0, 100);
    this.log(
      `${ride.rideId} matched with ${best.driverId} (${best.vehicleType}, ${bestDist.toFixed(2)} u away)`,
      "DEQUEUE",
      "O(1)",
    );
    this.emit();
    return { ride, driver: best };
  }

  // ---------------- drivers ----------------

  addDriver(
    name: string,
    x: number,
    y: number,
    vehicleType: VehicleType = "Cab Mini",
    vehicleNumber = "TN 00 XX 0000",
  ): Driver {
    this.driverCounter += 1;
    const id = `DRIVER-${String(this.driverCounter).padStart(2, "0")}`;
    const driver: Driver = {
      driverId: id,
      name,
      locationX: x,
      locationY: y,
      status: "Available",
      currentRide: null,
      vehicleType,
      vehicleNumber,
      rating: 4.5,
      trips: 0,
    };
    this.driverMap.set(id, driver);
    return driver;
  }

  setDriverStatus(driverId: string, status: DriverStatus) {
    const driver = this.driverMap.get(driverId); // O(1) hash map lookup
    if (!driver) throw new Error(`Driver "${driverId}" not found.`);
    driver.status = status;
    if (status === "Available") driver.currentRide = null;
    this.driverMap.set(driverId, driver);
    this.log(`${driverId} status set to ${status}`, "LOOKUP", "O(1)");
    this.emit();
  }

  resetDriver(driverId: string) {
    const driver = this.driverMap.get(driverId);
    if (!driver) throw new Error(`Driver "${driverId}" not found.`);
    driver.status = "Available";
    driver.currentRide = null;
    this.driverMap.set(driverId, driver);
    this.log(`${driverId} reset to Available`, "LOOKUP", "O(1)");
    this.emit();
  }

  setPricing(pricing: Partial<Pricing>) {
    const next = { ...this.pricing, ...pricing };
    if (next.baseFare < 0 || next.ratePerUnit < 0) {
      throw new Error("Pricing values cannot be negative.");
    }
    this.pricing = next;
    this.emit();
  }

  setProfile(profile: Partial<RiderProfile>) {
    const next = { ...this.profile, ...profile };
    if (!next.name.trim()) throw new Error("Profile name cannot be empty.");
    const coords = [next.home.x, next.home.y, next.work.x, next.work.y];
    if (coords.some((c) => !Number.isFinite(c))) {
      throw new Error("Saved place coordinates must be valid numbers.");
    }
    this.profile = next;
    this.log("Rider profile updated", "SYSTEM", "O(1)");
    this.emit();
  }

  // ---------------- bulk actions ----------------

  private seedDrivers() {
    SEED_DRIVERS.forEach((d) => {
      const driver = this.addDriver(d.name, d.x, d.y, d.vehicleType, d.vehicleNumber);
      driver.rating = d.rating;
      driver.trips = d.trips;
      this.driverMap.set(driver.driverId, driver);
    });
  }

  loadSampleData() {
    if (this.driverMap.size === 0) this.seedDrivers();

    const rides: Array<[string, Point, Point, DemandLevel, VehicleType]> = [
      ["Rahul", { x: 2, y: 3 }, { x: 10, y: 8 }, "Normal", "Cab Mini"],
      ["Priya", { x: 4, y: 9 }, { x: 14, y: 2 }, "High", "Bike"],
      ["Arjun", { x: 1, y: 1 }, { x: 6, y: 5 }, "Low", "Auto"],
      ["Neha", { x: 11, y: 12 }, { x: 3, y: 4 }, "Very High", "Cab Sedan"],
      ["Vikram", { x: 7, y: 7 }, { x: 16, y: 13 }, "Normal", "Cab SUV"],
    ];
    rides.forEach(([name, pickup, drop, demand, vehicleType]) => {
      const distance = euclideanDistance(pickup, drop);
      this.rideCounter += 1;
      this.queue.enqueue(
        new RideNode({
          rideId: `RIDE-${this.rideCounter}`,
          riderName: name,
          pickup,
          drop,
          distance: Math.round(distance * 100) / 100,
          fare: calculateFare(
            distance,
            demand,
            this.pricing.baseFare,
            this.pricing.ratePerUnit,
            VEHICLE_BY_TYPE[vehicleType].multiplier,
            1,
          ),
          demandLevel: demand,
          vehicleType,
        }),
      );
    });
    this.log(
      `Sample data loaded: ${this.driverMap.size} drivers, ${rides.length} rides`,
      "SYSTEM",
      "O(D + R)",
    );
    this.emit();
  }

  reset() {
    this.queue = new DispatchQueue();
    this.driverMap = new Map();
    this.logs = [];
    this.stats = { matched: 0, cancelled: 0 };
    this.rideCounter = 100;
    this.driverCounter = 0;
    this.history = [];
    this.lastCancelSteps = [];
    this.lastCancelledId = null;
    this.pricing = { baseFare: 50, ratePerUnit: 15 };
    this.seedDrivers();
    this.log(
      "Simulation reset — queue cleared, fleet re-registered in driverMap",
      "SYSTEM",
      "O(D)",
    );
    if (typeof window !== "undefined") localStorage.removeItem(STORAGE_KEY);
    this.emit(false);
  }

  // ---------------- persistence ----------------

  private persist() {
    if (typeof window === "undefined" || !this.hydrated) return;
    try {
      const data = {
        rides: this.queue.getAllRequests().map((n) => ({
          rideId: n.rideId,
          riderName: n.riderName,
          pickup: n.pickup,
          drop: n.drop,
          distance: n.distance,
          fare: n.fare,
          demandLevel: n.demandLevel,
          vehicleType: n.vehicleType,
          status: n.status,
          createdAt: n.createdAt,
        })),
        drivers: [...this.driverMap.values()],
        logs: this.logs,
        stats: this.stats,
        pricing: this.pricing,
        profile: this.profile,
        history: this.history,
        rideCounter: this.rideCounter,
        driverCounter: this.driverCounter,
      };
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch {
      /* storage unavailable — simulation still works in memory */
    }
  }

  hydrate() {
    if (this.hydrated || typeof window === "undefined") return;
    this.hydrated = true;
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) {
        this.seedDrivers();
        this.log(
          `${this.driverMap.size} drivers already on duty (driverMap seeded)`,
          "SYSTEM",
          "O(D)",
        );
        this.emit(false);
        return;
      }
      const data = JSON.parse(raw);
      this.queue = new DispatchQueue();
      for (const r of data.rides ?? []) {
        this.queue.enqueue(new RideNode(r));
      }
      this.driverMap = new Map(
        (data.drivers ?? []).map((d: Driver) => [
          d.driverId,
          { ...d, rating: d.rating ?? 4.5, trips: d.trips ?? 0, vehicleType: d.vehicleType ?? ("Cab Mini" as VehicleType), vehicleNumber: d.vehicleNumber ?? "—" },
        ]),
      );
      this.logs = data.logs ?? [];
      this.stats = data.stats ?? { matched: 0, cancelled: 0 };
      this.pricing = data.pricing ?? { baseFare: 50, ratePerUnit: 15 };
      this.profile = { ...DEFAULT_PROFILE, ...(data.profile ?? {}) };
      this.history = data.history ?? [];
      this.rideCounter = data.rideCounter ?? 100;
      this.driverCounter = data.driverCounter ?? 0;
      if (this.driverMap.size === 0) this.seedDrivers();
    } catch {
      /* corrupted state — start fresh */
      this.seedDrivers();
    }
    this.emit(false);
  }

  // ---------------- derived ----------------

  get drivers(): Driver[] {
    return [...this.driverMap.values()];
  }

  get rides(): RideNode[] {
    return this.queue.getAllRequests();
  }

  get availableCount(): number {
    return this.drivers.filter((d) => d.status === "Available").length;
  }

  get busyCount(): number {
    return this.drivers.filter((d) => d.status === "Busy").length;
  }

  get averageFare(): number {
    const rides = this.rides;
    if (!rides.length) return 0;
    return (
      Math.round((rides.reduce((s, r) => s + r.fare, 0) / rides.length) * 100) / 100
    );
  }

  /** available driver count per vehicle class — O(D) */
  availabilityByVehicle(): Record<string, number> {
    const out: Record<string, number> = {};
    for (const d of this.driverMap.values()) {
      if (d.status !== "Available") continue;
      out[d.vehicleType] = (out[d.vehicleType] ?? 0) + 1;
    }
    return out;
  }
}

export const store = new SimulationStore();
